### ISSUE TITLE
XMM-Newton Response Simulator

### ISSUE THREAD

**Issue by rjtanner** [lynx-x-ray-observatory/soxs#6]
Has anyone implemented XMM-Newton in the instrument simulator? I'm trying to compare my simulations to XMM-Newton data.

**Comment by jzuhone** [comment]
Hi @rjtanner,

(Sorry for never responding to the email)

I haven't done this because XMM-Newton seems a bit more complicated (in terms of layout of chips, FOV, etc), and SIXTE (https://www.sternwarte.uni-erlangen.de/research/sixte/) does a pretty good job of simulating it. If you make SIMPUT files with SOXS these can be used in SIXTE to to make XMM mocks. 

If we really want to do this in SOXS, we can try, but I won't be able to for some time. If you want to take a crack at it in the meantime please do!
